const fs=require('fs'),p=require('path');
const B='c:/Office/JFMS/src/pages';
function w(r,c){const f=p.join(B,r);fs.mkdirSync(p.dirname(f),{recursive:true});fs.writeFileSync(f,c);console.log('OK:'+r);}
function stub(file,name,title,sub){
  if(fs.existsSync(p.join(B,file)))return console.log('SKIP:'+file);
  w(file,`export default function ${name}(){return(<div><div className="page-header"><div><h1 className="page-title">${title}</h1><p className="page-subtitle">${sub}</p></div></div><div className="card"><p style={{color:'var(--gray-500)'}}>Screen content for ${title}</p></div></div>);}`);
}
const S=[
['admin/RolePermissions.jsx','RolePermissions','Role Permissions','View predefined role permission matrix'],
['admin/SabeelMaster.jsx','SabeelMaster','Sabeel No Master','Manage Sabeel household records'],
['admin/BankAccounts.jsx','BankAccounts','Bank Accounts','Manage bank accounts linked to this environment'],
['admin/IncomePurposeMapping.jsx','IncomePurposeMapping','Income Purpose to Bank Mapping','Configure bank mapping'],
['admin/AccessControl.jsx','AccessControl','Data & Notification Access Control','Control data access preferences'],
['takhmeen/TakhmeenDashboard.jsx','TakhmeenDashboard','Takhmeen Dashboard','Overview of Takhmeen collections for 1445H'],
['takhmeen/TakhmeenGroups.jsx','TakhmeenGroups','Takhmeen Groups','Manage Takhmeen contribution groups'],
['takhmeen/CreateTakhmeenGroup.jsx','CreateTakhmeenGroup','Create Takhmeen Group','Step-by-step wizard'],
['takhmeen/TakhmeenOverride.jsx','TakhmeenOverride','Individual Takhmeen Override','Override for a specific Sabeel'],
['takhmeen/TakhmeenApproval.jsx','TakhmeenApproval','Takhmeen Approval Queue','Approve or reject pending changes'],
['takhmeen/TakhmeenSchedule.jsx','TakhmeenSchedule','Payment Schedule (E-Mandate)','Set up recurring payments'],
['takhmeen/VoluntaryCampaign.jsx','VoluntaryCampaign','Voluntary Campaigns','Create and manage campaigns'],
['income/IncomeHome.jsx','IncomeHome','Income Entry','Record income from various sources'],
['income/TakhmeenIncomeEntry.jsx','TakhmeenIncomeEntry','Record Takhmeen Payment','Search Sabeel and record contribution'],
['income/VoluntaryIncomeEntry.jsx','VoluntaryIncomeEntry','Record Voluntary Contribution','Non-Takhmeen voluntary income'],
['income/OrgIncomeEntry.jsx','OrgIncomeEntry','Organization Income','Income from organizations'],
['income/EnayatIncomeEntry.jsx','EnayatIncomeEntry','Enayat Income','Income from Enayat organizations'],
['income/AgriIncomeEntry.jsx','AgriIncomeEntry','Agriculture Income','Income from Jamaat-owned land'],
['income/OtherIncomeEntry.jsx','OtherIncomeEntry','Other Income','Miscellaneous income entries'],
['income/IncomeListing.jsx','IncomeListing','Income Listing','All income entries recorded'],
['income/ReceiptCancellation.jsx','ReceiptCancellation','Receipt Cancellation','Request cancellation or data fix'],
['income/SuspenseManagement.jsx','SuspenseManagement','Suspense Entry Management','Unmatched bank credits'],
['income/IncomeDashboard.jsx','IncomeDashboard','Income Dashboard','Visual overview of collections'],
['deposits/DepositEntry.jsx','DepositEntry','Record Deposit','Create a deposit slip'],
['deposits/DepositListing.jsx','DepositListing','Deposits Listing','All deposit slips'],
['payments/PaymentsDashboard.jsx','PaymentsDashboard','Payments Dashboard','Overview of payments'],
['payments/VendorPaymentRequest.jsx','VendorPaymentRequest','Vendor Payment Request','Create vendor payment'],
['payments/PaymentApproval.jsx','PaymentApproval','Payment Approval Queue','Approve pending payments'],
['payments/BulkPayment.jsx','BulkPayment','Bulk Vendor Payment','Batch-process payments'],
['payments/MuminPayment.jsx','MuminPayment','Payment to Mumineen','Welfare payments and scholarships'],
['payments/DawatPayment.jsx','DawatPayment','Payment to Dawat','Dawat organization payments'],
['payments/UtilityPayment.jsx','UtilityPayment','Utility Payments','Electricity, water, internet bills'],
['payments/TaxPayment.jsx','TaxPayment','Tax Payments (TDS)','TDS liability and challan'],
['payments/SalaryPayment.jsx','SalaryPayment','Salary Payments','Staff salary register'],
['payments/PettyCash.jsx','PettyCash','Petty Cash','Withdrawal and replenishment'],
['payments/BankTransfer.jsx','BankTransfer','Bank to Bank Transfer','Inter-account transfers'],
['payments/PaymentListing.jsx','PaymentListing','All Payments','Complete payment records'],
['hybrid/PropertyRent.jsx','PropertyRent','Property Rent Module','Manage property rentals'],
['hybrid/HallBooking.jsx','HallBooking','Hall Booking','Calendar and booking management'],
['hybrid/OtherReceipts.jsx','OtherReceipts','Other Receipts & Liabilities','Advance payments and deposits'],
['reconciliation/ReconDashboard.jsx','ReconDashboard','Reconciliation Dashboard','Bank reconciliation status'],
['reconciliation/AutoRecon.jsx','AutoRecon','Auto Reconciliation (H2H)','Auto-matched bank transactions'],
['reconciliation/ManualRecon.jsx','ManualRecon','Manual Reconciliation','Upload and match bank statement'],
['reconciliation/SuspenseResolution.jsx','SuspenseResolution','Suspense Resolution','Resolve unmatched entries'],
['assets/InKindDonation.jsx','InKindDonation','In-Kind Donation Entry','Record donated assets'],
['assets/AssetRegister.jsx','AssetRegister','Asset Register','All capital assets'],
['journal/JournalEntry.jsx','JournalEntry','Journal Entry','Record journal voucher'],
['journal/JournalListing.jsx','JournalListing','Journal Entries Listing','All journal entries'],
['sabeel/SabeelSearch.jsx','SabeelSearch','Sabeel Profile Search','Search by Sabeel No or ITS ID'],
['sabeel/SabeelProfile.jsx','SabeelProfile','Sabeel Profile','Comprehensive household profile'],
['other/TallyExport.jsx','TallyExport','Tally-Compatible Export','Generate Tally export file'],
['other/NotificationCentre.jsx','NotificationCentre','Notification Centre','In-app notification feed'],
['reports/IncomeReport.jsx','IncomeReport','Income Reports','Filtered income report'],
['reports/ExpenseReport.jsx','ExpenseReport','Expense Reports','Filtered expense report'],
['reports/BalanceSheet.jsx','BalanceSheet','Balance Sheet','Assets, Liabilities, Net Position'],
['reports/IEStatement.jsx','IEStatement','Income & Expenditure Statement','Period-based I&E report'],
['reports/BankSummary.jsx','BankSummary','Bank-Wise Summary','Per-bank account summary'],
['reports/TakhmeenReport.jsx','TakhmeenReport','Takhmeen Collection Report','Purpose-wise collection'],
['reports/ComplianceReport.jsx','ComplianceReport','Compliance Report','PAN and TDS compliance'],
['fmb/FMBDashboard.jsx','FMBDashboard','FMB Dashboard','Thali operations overview'],
['fmb/PurchaseOrder.jsx','PurchaseOrder','Purchase Orders','Create and track POs'],
['fmb/GRNEntry.jsx','GRNEntry','Goods Receipt Note','Receive goods against PO'],
['fmb/DailyCostSheet.jsx','DailyCostSheet','Daily Cost Sheet','Daily FMB operational costs'],
['fmb/Inventory.jsx','Inventory','Inventory Management','Stock levels and alerts'],
['construction/ConstructionDashboard.jsx','ConstructionDashboard','Construction Project','Project phases and budget'],
['committee/CommitteeDashboard.jsx','CommitteeDashboard','Committee Dashboard','Madrasah environment'],
['waqf/WaqfDashboard.jsx','WaqfDashboard','Waqf / Trust','Property and maintenance'],
['migration/MigrationWizard.jsx','MigrationWizard','Data Migration Wizard','Step-by-step migration'],
['support/SupportHome.jsx','SupportHome','Support & Help','Search help articles'],
['support/RaiseTicket.jsx','RaiseTicket','Raise Support Ticket','Submit a support request'],
['support/FAQPage.jsx','FAQPage','Frequently Asked Questions','Expandable FAQ items'],
['mobile/MobilePreview.jsx','MobilePreview','Mobile App Preview','Mobile viewport screens'],
];
S.forEach(a=>stub(...a));
console.log('DONE: '+S.length+' pages processed');
